const config = {
  tagPrefixes: [{
    label: 'All',
    bgColor: '#FF7F50',
    adjustX: -7,
    fontColor: '',
    up: false,
    active: true
  }, {
    label: 'A',
    bgColor: '#2D5C7F',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'B',
    bgColor: '#E7475E',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'C',
    bgColor: '#248888',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'D',
    bgColor: '#6FA3A9',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'E',
    bgColor: '#3DC7BE',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'F',
    bgColor: '#8E3343',
    adjustX: 3,
    fontColor: '',
    up: false
  }, {
    label: 'G',
    bgColor: '#0FC9E7',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'H',
    bgColor: '#597FCA',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'I',
    bgColor: '#B9E1DC',
    adjustX: 5,
    fontColor: '',
    up: true
  }, {
    label: 'J',
    bgColor: '#AEE8E6',
    adjustX: 2,
    fontColor: '',
    up: false
  }, {
    label: 'K',
    bgColor: '#9FEED1',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'L',
    bgColor: '#B9D4F1',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'M',
    bgColor: '#7EB19F',
    adjustX: -2,
    fontColor: '',
    up: true
  }, {
    label: 'N',
    bgColor: '#3c6562',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'O',
    bgColor: '#C38B8B',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'P',
    bgColor: '#1989AC',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'Q',
    bgColor: '#FF007B',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'R',
    bgColor: '#D988BC',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'S',
    bgColor: '#FACC2E',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'T',
    bgColor: '#FF8585',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'U',
    bgColor: '#F2AE72',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'V',
    bgColor: '#C4F0C5',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'W',
    bgColor: '#ABCB89',
    adjustX: -2,
    fontColor: '',
    up: false
  }, {
    label: 'X',
    bgColor: '#F9B8BE',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: 'Y',
    bgColor: '#D0F0F7',
    adjustX: 0,
    fontColor: '',
    up: false
  }, {
    label: 'Z',
    bgColor: '#DED5C4',
    adjustX: 0,
    fontColor: '',
    up: true
  }, {
    label: '#',
    bgColor: '#8F8787',
    adjustX: 0,
    fontColor: '',
    up: false
  }]
}

export default config
