// 图片上传状态常量
const IMAGE_UPLOAD_INITIAL_STATE = 0
const SELECTED_IMAGE = 1
const IMAGE_UPLOADING = 2
const IMAGE_UPLOAD_FAILED = 3
const LOADING_IMAGE = 4
const LOADING_IMAGE_SUCCESS = 5
const LOADING_IMAGE_FAILED = 6


export {
  IMAGE_UPLOAD_INITIAL_STATE,
  SELECTED_IMAGE,
  IMAGE_UPLOADING,
  IMAGE_UPLOAD_FAILED,
  LOADING_IMAGE,
  LOADING_IMAGE_SUCCESS,
  LOADING_IMAGE_FAILED
}
